version: "3.8"

services:
  app:
    build:
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_URL=file:/app/data/local.db
      - SHOPIFY_STORE_DOMAIN=${SHOPIFY_STORE_DOMAIN}
      - SHOPIFY_ACCESS_TOKEN=${SHOPIFY_ACCESS_TOKEN}
      - SHOPIFY_GRAPHQL_API_ENDPOINT=${SHOPIFY_GRAPHQL_API_ENDPOINT}
    volumes:
      - app_data:/app/data
    restart: unless-stopped

volumes:
  app_data:
